#include "SpecialDayBackground.h"

#include <cstddef>
#include <cstdint>


// =========================================================
// EMBEDDED PNG ASSETS
// =========================================================
//
// IMPORTANT:
//
// Files are still named normally:
//
//     xmas_1.png
//     xmas_2.png
//     halloween_1.png
//     ...
//
// ESP-IDF automatically creates linker symbols:
//
//     _binary_xmas_1_png_start
//     _binary_xmas_1_png_end
//
// "start" and "end" are NOT extra asset files.
// They are only addresses generated by the linker.
//
// =========================================================

#define DECLARE_EMBEDDED_PNG(name)                  \
    extern const uint8_t name##_png_start[]         \
        asm("_binary_" #name "_png_start");         \
    extern const uint8_t name##_png_end[]           \
        asm("_binary_" #name "_png_end");


// =========================================================
// BIRTHDAY BACKGROUNDS
// =========================================================

DECLARE_EMBEDDED_PNG(ab)
DECLARE_EMBEDDED_PNG(mb)


// =========================================================
// NEW YEAR'S EVE
// =========================================================

DECLARE_EMBEDDED_PNG(anewyear_1)
DECLARE_EMBEDDED_PNG(anewyear_2)
DECLARE_EMBEDDED_PNG(anewyear_3)


// =========================================================
// HALLOWEEN
// =========================================================

DECLARE_EMBEDDED_PNG(halloween_1)
DECLARE_EMBEDDED_PNG(halloween_2)
DECLARE_EMBEDDED_PNG(halloween_3)
DECLARE_EMBEDDED_PNG(halloween_4)


// =========================================================
// MONTHIVERSARY
// =========================================================

DECLARE_EMBEDDED_PNG(monthi_1)
DECLARE_EMBEDDED_PNG(monthi_2)
DECLARE_EMBEDDED_PNG(monthi_3)
DECLARE_EMBEDDED_PNG(monthi_4)


// =========================================================
// NEW YEAR
// =========================================================

DECLARE_EMBEDDED_PNG(newyear_1)
DECLARE_EMBEDDED_PNG(newyear_2)
DECLARE_EMBEDDED_PNG(newyear_3)


// =========================================================
// VALENTINE
// =========================================================

DECLARE_EMBEDDED_PNG(val_1)
DECLARE_EMBEDDED_PNG(val_2)
DECLARE_EMBEDDED_PNG(val_3)
DECLARE_EMBEDDED_PNG(val_4)


// =========================================================
// CHRISTMAS
// =========================================================

DECLARE_EMBEDDED_PNG(xmas_1)
DECLARE_EMBEDDED_PNG(xmas_2)
DECLARE_EMBEDDED_PNG(xmas_3)
DECLARE_EMBEDDED_PNG(xmas_4)


namespace
{

// =========================================================
// ANIMATION STATE
// =========================================================

lv_timer_t* animationTimer =
    nullptr;


lv_obj_t* backgroundImage =
    nullptr;


const lv_image_dsc_t* const* activeFrames =
    nullptr;


int activeFrameCount =
    0;


int activeFrameIndex =
    0;


// =========================================================
// PNG IMAGE DESCRIPTORS
// =========================================================
//
// These descriptors do NOT contain 1.5 MB raw pixel arrays.
//
// descriptor.data simply points to the compressed PNG
// already embedded in flash.
//
// =========================================================

lv_image_dsc_t abImage = {};
lv_image_dsc_t mbImage = {};


lv_image_dsc_t anewyear1Image = {};
lv_image_dsc_t anewyear2Image = {};
lv_image_dsc_t anewyear3Image = {};


lv_image_dsc_t halloween1Image = {};
lv_image_dsc_t halloween2Image = {};
lv_image_dsc_t halloween3Image = {};
lv_image_dsc_t halloween4Image = {};


lv_image_dsc_t monthi1Image = {};
lv_image_dsc_t monthi2Image = {};
lv_image_dsc_t monthi3Image = {};
lv_image_dsc_t monthi4Image = {};


lv_image_dsc_t newyear1Image = {};
lv_image_dsc_t newyear2Image = {};
lv_image_dsc_t newyear3Image = {};


lv_image_dsc_t val1Image = {};
lv_image_dsc_t val2Image = {};
lv_image_dsc_t val3Image = {};
lv_image_dsc_t val4Image = {};


lv_image_dsc_t xmas1Image = {};
lv_image_dsc_t xmas2Image = {};
lv_image_dsc_t xmas3Image = {};
lv_image_dsc_t xmas4Image = {};


bool pngDescriptorsInitialized =
    false;


// =========================================================
// READ BIG-ENDIAN UINT32
// =========================================================
//
// PNG stores width/height in big-endian.
//
// PNG header:
//
// byte 16-19 = width
// byte 20-23 = height
//
// =========================================================

uint32_t readBigEndian32(
    const uint8_t* data
)
{
    return
        (
            static_cast<uint32_t>(
                data[0]
            )
            << 24
        )
        |
        (
            static_cast<uint32_t>(
                data[1]
            )
            << 16
        )
        |
        (
            static_cast<uint32_t>(
                data[2]
            )
            << 8
        )
        |
        static_cast<uint32_t>(
            data[3]
        );
}


// =========================================================
// INITIALIZE ONE PNG DESCRIPTOR
// =========================================================

void initializePngDescriptor(
    lv_image_dsc_t& descriptor,
    const uint8_t* start,
    const uint8_t* end
)
{
    if (
        start == nullptr
        ||
        end == nullptr
        ||
        end <= start
    ) {
        return;
    }


    const std::size_t size =
        static_cast<std::size_t>(
            end - start
        );


    // Need at least enough bytes for PNG signature
    // + width + height.
    if (
        size < 24
    ) {
        return;
    }


    // =====================================================
    // CHECK PNG SIGNATURE
    // =====================================================

    constexpr uint8_t PNG_SIGNATURE[8] = {
        0x89,
        0x50,
        0x4E,
        0x47,
        0x0D,
        0x0A,
        0x1A,
        0x0A
    };


    for (
        int i = 0;
        i < 8;
        ++i
    ) {
        if (
            start[i]
            != PNG_SIGNATURE[i]
        ) {
            return;
        }
    }


    // =====================================================
    // READ PNG DIMENSIONS
    // =====================================================

    const uint32_t width =
        readBigEndian32(
            start + 16
        );


    const uint32_t height =
        readBigEndian32(
            start + 20
        );


    // =====================================================
    // CREATE LVGL RAW PNG DESCRIPTOR
    // =====================================================
    //
    // The data remains compressed PNG.
    //
    // LVGL LodePNG decoder reads descriptor.data
    // and decodes it when the image is displayed.
    //
    // =====================================================

    descriptor.header.magic =
        LV_IMAGE_HEADER_MAGIC;


    descriptor.header.cf =
        LV_COLOR_FORMAT_RAW_ALPHA;


    descriptor.header.flags =
        0;


    descriptor.header.w =
        width;


    descriptor.header.h =
        height;


    descriptor.header.stride =
        0;


    descriptor.data_size =
        static_cast<uint32_t>(
            size
        );


    descriptor.data =
        start;
}


// =========================================================
// INITIALIZE ALL PNG DESCRIPTORS
// =========================================================

void initializePngDescriptors()
{
    if (
        pngDescriptorsInitialized
    ) {
        return;
    }


    // =====================================================
    // BIRTHDAYS
    // =====================================================

    initializePngDescriptor(
        abImage,
        ab_png_start,
        ab_png_end
    );


    initializePngDescriptor(
        mbImage,
        mb_png_start,
        mb_png_end
    );


    // =====================================================
    // NEW YEAR'S EVE
    // =====================================================

    initializePngDescriptor(
        anewyear1Image,
        anewyear_1_png_start,
        anewyear_1_png_end
    );


    initializePngDescriptor(
        anewyear2Image,
        anewyear_2_png_start,
        anewyear_2_png_end
    );


    initializePngDescriptor(
        anewyear3Image,
        anewyear_3_png_start,
        anewyear_3_png_end
    );


    // =====================================================
    // HALLOWEEN
    // =====================================================

    initializePngDescriptor(
        halloween1Image,
        halloween_1_png_start,
        halloween_1_png_end
    );


    initializePngDescriptor(
        halloween2Image,
        halloween_2_png_start,
        halloween_2_png_end
    );


    initializePngDescriptor(
        halloween3Image,
        halloween_3_png_start,
        halloween_3_png_end
    );


    initializePngDescriptor(
        halloween4Image,
        halloween_4_png_start,
        halloween_4_png_end
    );


    // =====================================================
    // MONTHIVERSARY
    // =====================================================

    initializePngDescriptor(
        monthi1Image,
        monthi_1_png_start,
        monthi_1_png_end
    );


    initializePngDescriptor(
        monthi2Image,
        monthi_2_png_start,
        monthi_2_png_end
    );


    initializePngDescriptor(
        monthi3Image,
        monthi_3_png_start,
        monthi_3_png_end
    );


    initializePngDescriptor(
        monthi4Image,
        monthi_4_png_start,
        monthi_4_png_end
    );


    // =====================================================
    // NEW YEAR
    // =====================================================

    initializePngDescriptor(
        newyear1Image,
        newyear_1_png_start,
        newyear_1_png_end
    );


    initializePngDescriptor(
        newyear2Image,
        newyear_2_png_start,
        newyear_2_png_end
    );


    initializePngDescriptor(
        newyear3Image,
        newyear_3_png_start,
        newyear_3_png_end
    );


    // =====================================================
    // VALENTINE
    // =====================================================

    initializePngDescriptor(
        val1Image,
        val_1_png_start,
        val_1_png_end
    );


    initializePngDescriptor(
        val2Image,
        val_2_png_start,
        val_2_png_end
    );


    initializePngDescriptor(
        val3Image,
        val_3_png_start,
        val_3_png_end
    );


    initializePngDescriptor(
        val4Image,
        val_4_png_start,
        val_4_png_end
    );


    // =====================================================
    // CHRISTMAS
    // =====================================================

    initializePngDescriptor(
        xmas1Image,
        xmas_1_png_start,
        xmas_1_png_end
    );


    initializePngDescriptor(
        xmas2Image,
        xmas_2_png_start,
        xmas_2_png_end
    );


    initializePngDescriptor(
        xmas3Image,
        xmas_3_png_start,
        xmas_3_png_end
    );


    initializePngDescriptor(
        xmas4Image,
        xmas_4_png_start,
        xmas_4_png_end
    );


    pngDescriptorsInitialized =
        true;
}


// =========================================================
// FRAME SETS
// =========================================================

const lv_image_dsc_t* anewyearFrames[] = {
    &anewyear1Image,
    &anewyear2Image,
    &anewyear3Image
};


const lv_image_dsc_t* halloweenFrames[] = {
    &halloween1Image,
    &halloween2Image,
    &halloween3Image,
    &halloween4Image
};


const lv_image_dsc_t* monthiFrames[] = {
    &monthi1Image,
    &monthi2Image,
    &monthi3Image,
    &monthi4Image
};


const lv_image_dsc_t* newyearFrames[] = {
    &newyear1Image,
    &newyear2Image,
    &newyear3Image
};


const lv_image_dsc_t* valFrames[] = {
    &val1Image,
    &val2Image,
    &val3Image,
    &val4Image
};


const lv_image_dsc_t* xmasFrames[] = {
    &xmas1Image,
    &xmas2Image,
    &xmas3Image,
    &xmas4Image
};


// =========================================================
// ANIMATION CALLBACK
// =========================================================

void animationTick(
    lv_timer_t*
)
{
    if (
        backgroundImage == nullptr
        ||
        activeFrames == nullptr
        ||
        activeFrameCount <= 1
    ) {
        return;
    }


    activeFrameIndex =
        (
            activeFrameIndex + 1
        )
        %
        activeFrameCount;


    lv_image_set_src(
        backgroundImage,
        activeFrames[
            activeFrameIndex
        ]
    );
}

} // namespace


// =========================================================
// STOP
// =========================================================

void SpecialDayBackground::stop()
{
    if (
        animationTimer != nullptr
    ) {
        lv_timer_delete(
            animationTimer
        );


        animationTimer =
            nullptr;
    }


    backgroundImage =
        nullptr;


    activeFrames =
        nullptr;


    activeFrameCount =
        0;


    activeFrameIndex =
        0;
}


// =========================================================
// CREATE
// =========================================================

void SpecialDayBackground::create(
    lv_obj_t* parent,
    SpecialEventType eventType
)
{
    stop();


    // =====================================================
    // PREPARE PNG DESCRIPTORS
    // =====================================================

    initializePngDescriptors();


    // =====================================================
    // CREATE BACKGROUND IMAGE
    // =====================================================

    backgroundImage =
        lv_image_create(
            parent
        );


    lv_obj_align(
        backgroundImage,
        LV_ALIGN_CENTER,
        0,
        0
    );


    lv_obj_remove_flag(
        backgroundImage,
        LV_OBJ_FLAG_CLICKABLE
    );


    activeFrameIndex =
        0;


    // =====================================================
    // SELECT SPECIAL-DAY BACKGROUND
    // =====================================================

    switch (
        eventType
    )
    {
        // -------------------------------------------------
        // MONTHIVERSARY
        // -------------------------------------------------

        case SpecialEventType::MONTHIVERSARY:

            activeFrames =
                monthiFrames;


            activeFrameCount =
                4;

            break;


        // -------------------------------------------------
        // HALLOWEEN
        // -------------------------------------------------

        case SpecialEventType::HALLOWEEN:

            activeFrames =
                halloweenFrames;


            activeFrameCount =
                4;

            break;


        // -------------------------------------------------
        // CHRISTMAS
        // -------------------------------------------------

        case SpecialEventType::CHRISTMAS:

            activeFrames =
                xmasFrames;


            activeFrameCount =
                4;

            break;


        // -------------------------------------------------
        // NEW YEAR'S EVE
        // -------------------------------------------------

        case SpecialEventType::NEW_YEARS_EVE:

            activeFrames =
                anewyearFrames;


            activeFrameCount =
                3;

            break;


        // -------------------------------------------------
        // NEW YEAR
        // -------------------------------------------------

        case SpecialEventType::NEW_YEAR:

            activeFrames =
                newyearFrames;


            activeFrameCount =
                3;

            break;


        // -------------------------------------------------
        // VALENTINE
        // -------------------------------------------------

        case SpecialEventType::VALENTINE:

            activeFrames =
                valFrames;


            activeFrameCount =
                4;

            break;


        // -------------------------------------------------
        // 21 SEPTEMBER BIRTHDAY
        // STATIC PNG
        // -------------------------------------------------

        case SpecialEventType::BIRTHDAY_SEPTEMBER:

            lv_image_set_src(
                backgroundImage,
                &mbImage
            );

            return;


        // -------------------------------------------------
        // 2 OCTOBER BIRTHDAY
        // STATIC PNG
        // -------------------------------------------------

        case SpecialEventType::BIRTHDAY_OCTOBER:

            lv_image_set_src(
                backgroundImage,
                &abImage
            );

            return;


        // -------------------------------------------------
        // NONE
        // -------------------------------------------------

        case SpecialEventType::NONE:
        default:

            lv_obj_delete(
                backgroundImage
            );


            backgroundImage =
                nullptr;

            return;
    }


    // =====================================================
    // SHOW FIRST FRAME
    // =====================================================

    lv_image_set_src(
        backgroundImage,
        activeFrames[0]
    );


    // =====================================================
    // START ANIMATION
    // =====================================================

    animationTimer =
        lv_timer_create(
            animationTick,
            400,
            nullptr
        );
}